# Generated by Django 4.1 on 2022-08-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteditems',
            name='dates',
            field=models.DateField(auto_now=True),
        ),
    ]
